#!/bin/bash

# Build for amd64
docker build --platform linux/amd64 -f $DOCKERFILE_PATH -t $IMAGE_NAME .

# Build for arm64
docker build --platform linux/arm64 -f $DOCKERFILE_PATH -t $IMAGE_NAME .

# Build for arm
docker build --platform linux/arm -f $DOCKERFILE_PATH -t $IMAGE_NAME .